# Generated by Django 2.2.7 on 2019-11-06 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_notesitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
